### PR TITLE
Implement metadata tags for social media previews, add OS version to macOS, and replace OS images with new ones

### LINKED ISSUE #11: Add OpenGraph metadata for improved preview when sharing website
Add metadata for improved preview when sharing website. This would offer a specific title, description, image, timestamp, etc. when the website URL is shared in a website, social media or instant messaging app.

Currently in LinkedIn, the preview is 

Screenshot from 2024-04-30 11-30-32

Example data to use:

    <meta name="og:updated_time" property="og:updated_time" content="1714338554">
    <meta name="og:site_name" property="og:site_name" content="Spyder IDE">
    <meta name="og:title" property="og:title" content="Intergalactic Spyder IDE">
    <meta name="og:type" property="og:type" content="website">
    <meta name="og:image" property="og:image" content="https://www.spyder-ide.org/screenshot.png">
    <meta name="og:image:width" property="og:image:width" content="5000">
    <meta name="og:image:height" property="og:image:height" content="2617">
    <meta name="og:url" property="og:url" content="https://www.spyder-ide.org/">
    <meta name="og:description" property="og:description" content="the Scientific Python Development Environment">

Note to:
- create screenshot.png (crop only screen from https://www.spyder-ide.org/spyder_website_banner.webp and run optipng on it)
- use the width and height
- update_time should be updated with each website update

All this will greatly improve the preview of the website.

### PR DESCRIPTION
**Pull request by conradolandia**
This PR implements OG metadata for social media sharing.

Fixes #11

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Hmm, is there something I'm missing here about how the opengraph tags and the download links/images are related or depend upon one another?

**Comment by conradolandia** [comment]
I'm not sure what you mean?

**Comment by ccordoba12** [comment]
@CAM-Gerlach, I think this is ready so could you clarify what you meant before?

**Review by CAM-Gerlach — APPROVED** [review]
Content LGTM now with the new images (aside from the unrelated changes conflated into one PR), thanks @conradolandia

**Pull request merged**
